[versions]
commonPagingVersion = "3.3.6"
jetbrains-compose = "1.7.3"
kotlinxCoroutinesCoreVersion = "1.7.3"
agp = "8.7.2"
kotlin = "2.1.10"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCoreVersion" }
paging-common = { module = "androidx.paging:paging-common", version.ref = "commonPagingVersion" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }
jetbrains-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "jetbrains-compose" }
jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetbrains-compose" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]
jetbrains-compose = ["jetbrains-compose-ui", "jetbrains-compose-material3", "jetbrains-compose-foundation", "jetbrains-compose-runtime"]